FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./

ARG NPM_MIRROR=https://mirror-npm.runflare.com
RUN npm --registry=$NPM_MIRROR install 

COPY . .

RUN npm run build backend

FROM node:20-alpine AS runner

WORKDIR /app
COPY --from=builder /app/dist/apps/backend ./dist
COPY --from=builder /app/package*.json .

ENV NODE_ENV=production
ARG NPM_MIRROR=https://mirror-npm.runflare.com
RUN npm --registry=$NPM_MIRROR install  --omit=dev

USER node
CMD ["node", "dist/main"]
